# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meali_layout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for meali_layout
	pod 'SnapKit'
	pod 'RxDataSources'
  	pod 'RxSwift'
	pod 'Action'
	pod 'RxCocoa'

  target 'meali_layoutTests' do
    inherit! :search_paths
    # Pods for testing


  end

  target 'meali_layoutUITests' do
    # Pods for testing
  end

end
